### ISSUE TITLE
I try to run in localhost, but something wrong.

### ISSUE THREAD

**Issue by shownb** [SheepTester/scratch-gui#10]
I have modifyed the files like what the readme.md said. but I used the latest scratch-gui and scratch-vm.
yes ,the extensions can be loaded through url.
but still have error.
```
[Log] vm – "warn" – "Primitive rejected promise: " – DataCloneError: The object can not be cloned. — shared-dispatch.js:137 (lib.min.js, line 233846)
DataCloneError: The object can not be cloned. — shared-dispatch.js:137postMessage（匿名函数） — shared-dispatch.js:137initializePromisePromise_remoteTransferCall — shared-dispatch.js:126transferCall — shared-dispatch.js:82call — shared-dispatch.js:59（匿名函数） — extension-manager.js:420（匿名函数） — extension-manager.js:437execute — execute.js:523stepThread — sequencer.js:212stepThreads — sequencer.js:128_step — runtime.js:2031（匿名函数） — runtime.js:2552
```

and I git clone your scratch-gui and scratch-vm version,it work perfect.

**Comment by SheepTester** [comment]
Which extension are you using? I think your extension returned something like a function or `global`. Since unofficial extensions like ones loaded by the URL are run in a sandboxed worker, all data that go between the worker and Scratch must be cloneable

**Comment by MariamQusai** [comment]
I am also experiencing the same issue:
I cloned your scratch-gui and scratch-vm 
i tried it with the below supplied  extension.   
https://sheeptester.github.io/javascripts/utilities.js

**Comment by shownb** [comment]
> I am also experiencing the same issue:
> I cloned your scratch-gui and scratch-vm
> i tried it with the below supplied extension.
> https://sheeptester.github.io/javascripts/utilities.js

you need to use this without https
use it in this way : ?url=http://xxx.com/javascripts/utilities.js

**Comment by MariamQusai** [comment]
I tried again no luck. 
this is exactly what i did 
cloned scratch-gui and scratch-vm from this repo
cd scratch-vm & npm install, npm link
cd scratch-gui & npm link scratch-vm, npm install

**Comment by MariamQusai** [comment]
below is my error message
lib.min.js:236699 vm Primitive rejected promise:  DOMException: Failed to execute 'postMessage' on 'Worker': function Date() { [native code] } could not be cloned.
    at http:/xxx/lib.min.js:267451:20
    at new Promise (<anonymous>)
    at CentralDispatch._remoteTransferCall (xxx/lib.min.js:267434:14)
    at CentralDispatch.transferCall (http://xxx/lib.min.js:267373:45)
    at CentralDispatch.call (http://xxx/lib.min.js:267341:32)
    at serviceObject (http://xxx/lib.min.js:276775:35)
    at blockInfo.func (http://xxx/lib.min.js:276795:22)
    at execute (http://xxx/lib.min.js:270389:34)
    at Sequencer.stepThread (http://xxx/lib.min.js:274348:11)
    at Sequencer.stepThreads (http://xxx:lib.min.js:274254:18)

**Comment by SheepTester** [comment]
@MariamQusai Were you testing your own extension? If so, it is possible that you returned a `Date` object in the extension, but because these extensions are run in a web worker, all data that are returned must be cloneable

**Comment by MariamQusai** [comment]
@SheepTester actually i was testing this extension: https://sheeptester.github.io/javascripts/utilities.js

**Comment by MariamQusai** [comment]
@SheepTester I dont think there is anything rong with the extensions. they work fine on https://sheeptester.github.io/scratch-gui/ but not on my local copy

**Comment by kumar1250324** [comment]
@SheepTester I am facing the same issue on my local copy

**Comment by SheepTester** [comment]
@MariamQusai Might this be because you didn't link scratch-vm to scratch-gui?

**Comment by SheepTester** [comment]
Closing due to inactivity
