### ISSUE TITLE
below is my error message which i faced 

### ISSUE THREAD

**Issue by kumar1250324** [SheepTester/scratch-gui#21]
below is my error message
lib.min.js:236699 vm Primitive rejected promise:  DOMException: Failed to execute 'postMessage' on 'Worker': function Date() { [native code] } could not be cloned.
    at http:/xxx/lib.min.js:267451:20
    at new Promise (<anonymous>)
    at CentralDispatch._remoteTransferCall (xxx/lib.min.js:267434:14)
    at CentralDispatch.transferCall (http://xxx/lib.min.js:267373:45)
    at CentralDispatch.call (http://xxx/lib.min.js:267341:32)
    at serviceObject (http://xxx/lib.min.js:276775:35)
    at blockInfo.func (http://xxx/lib.min.js:276795:22)
    at execute (http://xxx/lib.min.js:270389:34)
    at Sequencer.stepThread (http://xxx/lib.min.js:274348:11)
    at Sequencer.stepThreads (http://xxx:lib.min.js:274254:18)

_Originally posted by @MariamQusai in https://github.com/SheepTester/scratch-gui/issues/10#issuecomment-593963685_

**Comment by SheepTester** [comment]
Hmm, do you think this might be because you didn't link the other forked repositories?
